language: node_js
node_js:
- '4'
sudo: false
cache: directories - $HOME/.npm - $HOME/.cache
before_install:
- npm config set spin false
- npm install -g bower
- npm install -g ember
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
- openssl aes-256-cbc -K $encrypted_62b5f12cee6a_key -iv $encrypted_62b5f12cee6a_iv -in config/.npmrc.enc -out $HOME/.npmrc -d
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: script
  script: npm-deploy.sh
  on:
    repo: eHealthAfrica/hospitalrun-frontend
    branch: develop
  on:
    repo: eHealthAfrica/hospitalrun-frontend
    branch: stage
  on:
    repo: eHealthAfrica/hospitalrun-frontend
    branch: master
  on:
    repo: eHealthAfrica/hospitalrun-frontend
    branch: eHA/Polyclinic

after_deploy:
  - script/server_build.sh
